LibraryManagementSystem/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from core import views as core_views

urlpatterns = [
    path('', core_views.landing, name='landing'),
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('login/', core_views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', core_views.register, name='register'),
]

books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:book_id>/', views.detail, name='detail'),
    path('search/', views.search, name='search'),
    path('confirm_add/<str:isbn>/', views.confirm_add, name='confirm_add'),
    path('delete/<int:book_id>/', views.delete, name='delete'),



]

core/urls.py
from django.urls import path
from .views import landing

urlpatterns = [
    path('', landing, name='landing'),
]

books/models.py
from django.contrib.auth.models import User
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    pub_date = models.CharField(max_length=200)
    isbn = models.CharField(max_length=200)
    thumbnail = models.URLField()
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title

core/models.py
from django.db import models

# Create your models here.

books/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Book
import requests


def get_book_data(query):
    if len(query) in [10, 13]:  # If it's an ISBN
        response = requests.get(
            f"https://www.googleapis.com/books/v1/volumes?q=isbn:{query}")
    else:  # If it's a book title
        response = requests.get(
            f"https://www.googleapis.com/books/v1/volumes?q=intitle:{query}")

    data = response.json()

    if response.status_code != 200 or "items" not in data:
        return None

    books_data = []
    for item in data["items"]:
        book_data = item["volumeInfo"]
        books_data.append({
            "title": book_data.get("title", ""),
            "author": ", ".join(book_data.get("authors", [])),
            "pub_date": book_data.get("publishedDate", ""),
            "isbn": book_data.get("industryIdentifiers", [{"identifier": None}])[0]["identifier"],
            "thumbnail": book_data.get("imageLinks", {}).get("thumbnail", "")
        })

    return books_data


def index(request):
    all_books = Book.objects.filter(user=request.user)
    return render(request, 'books/index.html', {'all_books': all_books})


def detail(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, 'books/detail.html', {'book': book})


def search(request):
    if request.method == 'POST':
        query = request.POST.get('query')

        books_data = get_book_data(query)
        if books_data:
            # Save book data into session
            request.session['books_data'] = books_data
            return render(request, 'books/search_results.html', {'books': books_data})
        else:
            messages.warning(request, 'Book not found or invalid query')
    return render(request, 'books/index.html', {'all_books': Book.objects.filter(user=request.user)})


def confirm_add(request, isbn):
    if 'books_data' not in request.session:
        return redirect('books:index')

    books_data = request.session['books_data']
    book_data = next(
        (book for book in books_data if book["isbn"] == isbn), None)

    if book_data is None:
        messages.error(request, 'Book not found')
        return redirect('books:index')

    if request.method == 'POST':
        if Book.objects.filter(isbn=isbn, user=request.user).exists():
            messages.warning(
                request, 'You already have this book in your library')
        else:
            new_book = Book(user=request.user, **book_data)
            new_book.save()
            messages.success(request, 'Book added successfully')
        return redirect('books:index')

    return render(request, 'books/confirm_add.html', {'book': book_data})


def delete(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    book.delete()
    messages.success(request, 'Book deleted successfully')
    return redirect('books:index')

core/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login as auth_login, authenticate
from django.shortcuts import render, redirect
from django.contrib import messages


def landing(request):
    return render(request, 'landing.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            return redirect('books:index')
        else:
            messages.error(request, 'Invalid username or password.')
    return render(request, 'login.html')


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            if User.objects.filter(username=username).exists():
                messages.error(request, 'Username already exists.')
                return redirect('register')
            else:
                user = form.save()
                auth_login(request, user)
                return redirect('books:index')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})

books/templates/books/confirm_add.html
<!DOCTYPE html>
<html>
	<head>
		<title>Confirm Addition</title>
		<!-- Add Bootstrap or other styling libraries here -->
	</head>
	<body>
		<h1>Confirm Addition</h1>
		<h2>{{ book.title }}</h2>
		<p>
			<b>Author:</b> {{ book.author }}<br />
			<b>Publication Date:</b> {{ book.pub_date }}<br />
			<b>ISBN:</b> {{ book.isbn }}
		</p>
		<img src="{{ book.thumbnail }}" alt="{{ book.title }}" />
		<form method="POST">
			{% csrf_token %}
			<button type="submit">Add to My Book List</button>
		</form>
	</body>
</html>

books/templates/books/index.html
<head>
	<title>Book Library</title>
	<link
		rel="stylesheet"
		href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
	/>
	<style>
		.card-image {
			width: 100%;
			height: 200px;
			object-fit: contain;
		}
		.card {
			height: 100%;
		}
	</style>
</head>
<body>
	<div class="container py-5">
		<!-- Messages Block -->
		{% if messages %}
		<div class="mt-3">
			{% for message in messages %}
			<div class="alert alert-{{ message.tags }}">{{ message }}</div>
			{% endfor %}
		</div>
		{% endif %}

		<!-- Search Book Section -->
		<div class="row justify-content-center mb-5">
			<div class="col-lg-6">
				<h2 class="text-center">Reading List</h2>
				<form
					action="{% url 'books:search' %}"
					method="POST"
					class="mt-4"
				>
					{% csrf_token %}
					<div class="form-group">
						<label for="query"
							>Search for a book by ISBN or title:</label
						>
						<input
							id="query"
							type="text"
							name="query"
							class="form-control"
							required
						/>
					</div>
					<div class="form-group">
						<input
							type="submit"
							value="Search Book"
							class="btn btn-primary"
						/>
					</div>
				</form>
			</div>
		</div>

		<!-- Book List -->
		{% if all_books %}
		<div class="row row-cols-1 row-cols-md-3">
			{% for book in all_books %}
			<div class="col mb-4">
				<div class="card h-100 shadow-sm">
					<img
						src="{{ book.thumbnail }}"
						alt="{{ book.title }}"
						class="card-img-top card-image"
					/>
					<div class="card-body">
						<h5 class="card-title">{{ book.title }}</h5>
						<p class="card-text">
							<b>Author:</b> {{ book.author }}<br />
							<b>Publication Date:</b> {{ book.pub_date }}<br />
							<b>ISBN:</b> {{ book.isbn }}
						</p>
						<!-- DELETE BUTTON -->
						<form
							action="{% url 'books:delete' book.id %}"
							method="POST"
						>
							{% csrf_token %}
							<button type="submit" class="btn btn-danger">
								Delete
							</button>
						</form>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
		{% else %}
		<p class="text-center">No books found.</p>
		{% endif %}
	</div>
</body>

books/templates/books/search_results.html
<head>
	<link
		rel="stylesheet"
		href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
	/>
	<!-- Add any other head elements you need here -->
</head>
<style>
	.card {
		display: grid; /* Use CSS Grid layout */
		grid-template-rows: auto 1fr auto; /* Divide the card into three sections */
	}
	.card-img-top {
		width: 100%;
		min-height: 200px;
		object-fit: cover;
	}
</style>
<body>
	<div class="container py-5">
		<h2 class="text-center">Search Results</h2>

		<!-- Display any messages -->
		{% if messages %}
		<div class="alert alert-info">
			{% for message in messages %} {{ message }} {% endfor %}
		</div>
		{% endif %}

		<!-- Search Results -->
		{% if books %}
		<div class="row">
			{% for book in books %}
			<div class="col-lg-4 col-md-6 mb-4">
				<div class="card h-100">
					<img
						src="{{ book.thumbnail }}"
						class="card-img-top"
						alt="{{ book.title }}"
					/>
					<div class="card-body">
						<h5 class="card-title">{{ book.title }}</h5>
						<p class="card-text">
							<b>Author:</b> {{ book.author }}<br />
							<b>Publication Date:</b> {{ book.pub_date }}<br />
							<b>ISBN:</b> {{ book.isbn }}
						</p>
					</div>
					<div class="card-footer">
						<form
							action="{% url 'books:confirm_add' book.isbn %}"
							method="POST"
						>
							{% csrf_token %}
							<input
								type="submit"
								value="Add to my books"
								class="btn btn-primary btn-block"
							/>
						</form>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
		{% else %}
		<p class="text-center text-muted">
			No books found. Please try again with a different search term.
		</p>
		{% endif %}
	</div>
</body>

core/templates/landing.html
<!DOCTYPE html>
<html>
	<head>
		<title>Welcome to Book Library</title>
		<link
			rel="stylesheet"
			href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
		/>
		<style>
			.container {
				height: 100vh;
				display: flex;
				justify-content: center;
				align-items: center;
				flex-direction: column;
			}
			.landing-container {
				text-align: center;
				font-size: 1.5em;
			}
		</style>
	</head>
	<body>
		<div class="container">
			{% if messages %}
			<div class="messages">
				{% for message in messages %}
				<div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
				{% endfor %}
			</div>
			{% endif %}
			<div class="landing-container">
				<h1>Welcome to The Book List</h1>
				<p>A place to manage and explore your favourite books, and add it to you read list!</p>
				<a href="{% url 'login' %}" class="btn btn-primary btn-lg"
					>Get Started</a
				>
			</div>
		</div>
	</body>
</html>

core/templates/login.html
<!DOCTYPE html>
<html>
	<head>
		<title>Login to Book Library</title>
		<link
			rel="stylesheet"
			href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
		/>
		<style>
			.container {
				height: 100vh;
				display: flex;
				justify-content: center;
				align-items: center;
				flex-direction: column;
			}
			.form-group {
				display: flex;
				justify-content: center;
				align-items: center;
				flex-direction: column;
				font-size: 1.3em;
			}
		</style>
	</head>
	<body>
		<div class="container">
			{% if messages %}
			<div class="messages">
				{% for message in messages %}
				<div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
				{% endfor %}
			</div>
			{% endif %}
			<form method="POST" class="mt-4">
				{% csrf_token %}
				<div class="form-group">
					<label for="username">Username:</label>
					<input
						id="username"
						type="text"
						name="username"
						class="form-control"
						required
					/>
				</div>
				<div class="form-group">
					<label for="password">Password:</label>
					<input
						id="password"
						type="password"
						name="password"
						class="form-control"
						required
					/>
				</div>
				<div class="form-group">
					<input
						type="submit"
						value="Login"
						class="btn btn-primary"
					/>
				</div>
				<p class="mt-3">
					Don't have an account?
					<a href="{% url 'register' %}">Register</a>
				</p>
			</form>
		</div>
	</body>
</html>

core/templates/register.html
<!DOCTYPE html>
<html>
	<head>
		<title>Register</title>
		<link
			rel="stylesheet"
			href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
		/>
		<style>
			.container {
				height: 100vh;
				display: flex;
				justify-content: center;
				align-items: center;
				flex-direction: column;
			}
			.form-group {
				display: flex;
				justify-content: center;
				align-items: center;
				flex-direction: column;
				font-size: 1.3em;
			}
		</style>
	</head>
	<body>
		<div class="container">
			{% if messages %}
			<div class="messages">
				{% for message in messages %}
				<div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
				{% endfor %}
			</div>
			{% endif %}
			<form method="POST" class="mt-4">
				{% csrf_token %}
				<div class="form-group">
					<label for="{{ form.username.id_for_label }}"
						>Username:</label
					>
					{{ form.username }}
					<small class="form-text text-muted"
						>Required. 150 characters or fewer. Letters, digits
						and @/./+/-/_ only.</small
					>
				</div>
				<div class="form-group">
					<label for="{{ form.password1.id_for_label }}"
						>Password:</label
					>
					{{ form.password1 }}
					<small class="form-text text-muted">
						Your password can't be too similar to your other
						personal information.<br />
						Your password must contain at least 8 characters.<br />
						Your password can't be a commonly used password.<br />
						Your password can't be entirely numeric.
					</small>
				</div>
				<div class="form-group">
					<label for="{{ form.password2.id_for_label }}"
						>Password confirmation:</label
					>
					{{ form.password2 }}
					<small class="form-text text-muted">
						Enter the same password as before, for verification.
					</small>
				</div>
				<div class="form-group">
					<input
						type="submit"
						value="Register"
						class="btn btn-primary"
					/>
				</div>
			</form>
			<p class="mt-3 text-center">
				Already have an account?
				<a href="{% url 'login' %}">Login</a>
			</p>
		</div>
	</body>
</html>